//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGAMT2010.TravellingSalesman {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BestGAInfo", Namespace="http://schemas.datacontract.org/2004/07/TSGALib")]
    [System.SerializableAttribute()]
    public partial class BestGAInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FitnessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] memField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fitness {
            get {
                return this.FitnessField;
            }
            set {
                if ((this.FitnessField.Equals(value) != true)) {
                    this.FitnessField = value;
                    this.RaisePropertyChanged("Fitness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] mem {
            get {
                return this.memField;
            }
            set {
                if ((object.ReferenceEquals(this.memField, value) != true)) {
                    this.memField = value;
                    this.RaisePropertyChanged("mem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TravellingSalesman.ITSGA", CallbackContract=typeof(TSGAMT2010.TravellingSalesman.ITSGACallback))]
    public interface ITSGA {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITSGA/RunGA")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TSGAMT2010.TravellingSalesman.BestGAInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        void RunGA(object[] PointsList, int numThreads);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITSGACallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITSGA/OnComputeGA")]
        void OnComputeGA(TSGAMT2010.TravellingSalesman.BestGAInfo res);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITSGAChannel : TSGAMT2010.TravellingSalesman.ITSGA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TSGAClient : System.ServiceModel.DuplexClientBase<TSGAMT2010.TravellingSalesman.ITSGA>, TSGAMT2010.TravellingSalesman.ITSGA {
        
        public TSGAClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TSGAClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TSGAClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TSGAClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TSGAClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RunGA(object[] PointsList, int numThreads) {
            base.Channel.RunGA(PointsList, numThreads);
        }
    }
}
